name: ez_vote
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^1.3.1
  random_color: ^1.0.3
  firebase_auth: ^0.14.0+5
  firebase_database:
  cloud_firestore: ^0.12.9+4
  curved_navigation_bar: ^0.3.1
  flutter_fluid_slider: ^0.0.1
  font_awesome_flutter: ^8.5.0
  flare_flutter: ^1.5.9
  nima: ^1.0.0
  service_locator: ^1.0.0
  url_launcher: ^5.0.3
  get_it: ^1.0.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flare/robot1.nma
    - assets/flare/robot 1.png


    - assets/images/multioption.jpg
    - assets/images/AB.jpg
    - assets/images/rating.jpg
    - assets/images/agreeRating.jpg
    - assets/images/bg.jpg
    - assets/images/bg.png


    - assets/icons/political.png
    - assets/icons/politicalW.png
    - assets/icons/science.png
    - assets/icons/scienceW.png
    - assets/icons/sport.png
    - assets/icons/sportW.png
    - assets/icons/technology.png
    - assets/icons/technologyW.png
    - assets/icons/news.png
    - assets/icons/newsW.png
    - assets/icons/lifestyle.png
    - assets/icons/lifestyleW.png
    - assets/icons/everything.png
    - assets/icons/everythingW.png
    - assets/icons/business.png
    - assets/icons/businessW.png
    - assets/icons/art.png
    - assets/icons/artW.png
    - assets/icons/multipleoptions.png
    - assets/icons/ab.png
    - assets/icons/rating.png
    - assets/icons/agreedisagree.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico.ttf

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/font/Poppins-Black.ttf

    - family: Ghostz
      fonts:
        - asset: assets/font/Ghostz.ttf

    - family: Assassin
      fonts:
        - asset: assets/font/Assassin.ttf

    - family: Letrera
      fonts:
        - asset: assets/font/letrera.ttf

    - family: Vatican
      fonts:
        - asset: assets/font/Vatican.ttf

    - family: Odachi
      fonts:
        - asset: assets/font/Odachi.otf

    - family: Skyfont
      fonts:
        - asset: assets/font/Skyfont.otf

    - family: Rumble
      fonts:
        - asset: assets/font/Rumble.otf

    - family: Roboto-Black
      fonts:
       - asset: assets/font/Roboto-Black.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  uses-material-design: true
